library(ggplot2)
setwd("/Users/YanYang/code/exdata-data-NEI_data/")
clsf <- readRDS("Source_Classification_Code.rds")
pm <- readRDS("summarySCC_PM25.rds")
m.bc <- subset(pm, pm$type == "ON-ROAD" & fips == "24510")
m.bc[7] <- rep("Baltimore", nrow(m.bc))
m.la <- subset(pm, pm$type == "ON-ROAD" & fips == "06037")
m.la[7] <- rep("Los Angeles", nrow(m.la))
use <- rbind(m.bc, m.la)
names(use)[7] <- c("City")
use$year <- as.factor(use$year)
use$City <- as.factor(use$City)
png(filename = "plot6.png")
g <- ggplot(use, aes(x = year, y = Emissions))
g + geom_bar(stat = "identity", aes(fill = year)) + facet_grid(.~ City) + scale_fill_manual(values = topo.colors(4)) + theme_bw() + labs(title = "Total Motor Vehicle Emissions in Baltimore and Los Angeles") + labs(x = "Year", y = "Total Emissions(Ton)")
dev.off()