library(ggplot2)
setwd("/Users/YanYang/code/exdata-data-NEI_data/")
clsf <- readRDS("Source_Classification_Code.rds")
pm <- readRDS("summarySCC_PM25.rds")
bc <- subset(pm, fips == "24510")
bc$year <- as.factor(bc$year)
png(filename = "plot3.png")
g <- ggplot(bc, aes(x = year, y = Emissions, fill = year))
g + geom_bar(stat="identity") + facet_grid(.~ type) + theme_bw(base_family = "Times") + labs(title = "PM2.5 Emission in Baltimore City by Type") + labs(x = "Year", y = "PM2.5 Emission(Ton)") + scale_fill_manual(values=heat.colors(4))
dev.off()