setwd("/Users/YanYang/code/exdata-data-NEI_data/")
clsf <- readRDS("Source_Classification_Code.rds")
pm <- readRDS("summarySCC_PM25.rds")
bc <- subset(pm, fips == "24510")
sum <- tapply(bc$Emissions, bc$year, sum)
png(filename = "plot2.png")
par(mar = c(5,5,4,2))
barplot(sum, main = "Total PM2.5 Emissions in Baltimore City", xlab = "Year", ylab = "PM2.5 Emission(Ton)", col = "blue", lwd = 3, ylim = c(0, 3500))
dev.off()